import React from 'react'
import Head from 'next/head'
export default function aboutus() {
  return (
    <>
    <Head>
        <title>About Us | TAD.STUDIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1>ABOUT US || TAD.STUDIO</h1>
    </>
    
  )
}
